---
title: "Up-and-Down Designs: the `upndown` Package"
author: "Assaf Oron"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Up-and-Down Basics and the 'upndown' Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
#### Note to self: Use this whenever editing the vignette for resubmission/rebuild
# tools::buildVignettes(dir = '.',  tangle=TRUE)
# dir.create("inst/doc")
# file.copy(dir("vignettes", full.names=TRUE), "inst/doc", overwrite=TRUE)
# (from SoF: https://stackoverflow.com/questions/10266963/moving-files-between-folders)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

## Background

Up-and-Down designs (UDDs) have the unique distinction of being, in all likelihood, the most popular experimental design that present-day statisticians have <u>never</u> heard of. Originally developed by statisticians and successfully introduced by them in the mid-20th Century to a staggering array of application fields, in subsequent decades academic statistical interest has wandered elsewhere.

Nevertheless, UDDs have persisted. Studies using UDDs are routinely published in anesthesiology, toxicology, materials science, dentistry, electrical engineering, and other fields -- as well as the fields in which it was originally developed: sensory studies and explosive testing. Thus, UDDs are far from being an *"endangered"* design; rather, they are **statistically underserved.**

The `upndown` package presents basic computational tools and shortcuts to help modernize and standardize UDD usage, and make insights about the design more accessible to practitioners and statisticians. It incorporates results by the handful statisticians who have happened to wander *into* UDD methodology (or stay with it) in recent decades. As a side effect, we provide methodological reference for statisticians and analysts wishing to learn more about UDDs. 

For UDD estimation and data visualization we rely heavily upon the [`cir`](https://cran.r-project.org/web/packages/cir/) package. That package codifies Centered Isotonic Regression (CIR),^[Oron AP, Flournoy N. Centered Isotonic Regression: Point and Interval Estimation for Dose-Response Studies. *Stat Biopharm Res* 2017;9(3):258-267.] an improvement of isotonic regression motivated by the needs of UDDs and of dose-response studies in general. The `upndown` utilities using `cir` functions emphasize ease of use, and do not necessitate in-depth familiarity with the latter package.

## What Makes a Design "Up-and-Down"?

The hallmark of a genuine UDD is the **target-centered random walk** it generates over the dose levels. To do that, it requires^[Oron AP, Souter MJ, Flournoy N. Understanding Research Methods: Up-and-down Designs for Dose-finding. *Anesthesiology* 2022; 137:137–50.]

  1. A binary response *(a ternary response might also be UDD-compatiable, but hasn't been attempted in practice to our knowledge)*.
  2. Treatments ordered as a discrete set of increasing doses of the same treatment or drug. Preferably, the allowed doses are uniformly spaced in an algebraic or geometric sequence.
  3. The probability of positive response must maintain the same direction of change (increasing or decreasing) with increasing dose. For notational simplicity we assume that it is increasing, and denote the relationship between dose and positive-response probabilities by the function F(x); x being the dose-magnitude variable (Figure 1).
  4. Doses are allocated to patients sequentially, and only allow for increasing the dose by one level, decreasing by one level, or repeating the same dose. Hence the design’s name “up-and-down”, or (in sensory studies and materials testing) *“the Staircase Method.”*^[Garcìa-Perez MA. Forced-Choice staircases with fixed step sizes: asymptotic and small-sample properties. *Vision Res* 1998;38:1861-1881.]
  5. Dose-transition rules based on the doses and responses of <u>the last patient or several patients</u>, rather than on all patient data going back to the beginning of the experiment. Furthermore, **the rules do not use any estimated quantity that changes during the study.**
  
The fifth and last element might be responsible for UDDs falling out of statistical fashion. In Phase I trial design in particular, current statistical orthodoxy maintains that anything short of using the entire sample for each dosing decision, is an indefensible waste of precious information. 

In our humble opinion, this view 

 - confounds the task of data collection - which may not necessarily benefit from carrying the entire dataset *"on its back"* at each step^[Oron AP, Hoff PD. Small-Sample Behavior of Novel Phase I Cancer Trial Designs. *Clin Trials* 2013;10(1):63-80. With discussion on pp. 81-92.] - with the task of estimation, at which point UDDs <u>do</u> use the entire sample;
 - brushes aside some basic statistical realities of small-sample, binary-response uncertainty; 
 - and last but not least, ignores UDDs' proven properties and impressive track record.
 
But I digress.

## Experimental Examples






